---
- hosts: wordpress
  become: yes
  roles:
    - wordpress
  vars_prompt:
    - name: "dbpassword"
      prompt: "Please enter MySQL wordpress user password"
      default: "wordpress"
    - name: "dbname"
      prompt: "Please enter MySQL wordpress user name"
      default: "wordpress"
