---
- black:
  - name: WEBサーバ(Apache 2.2系)がインストールされている
    yum:
      pkg: httpd
      state: installed

  - name: ドキュメントルートが作成されている
    file:
      dest: "{{ documentroot }}"
      state: directory
      owner: apache
      group: apache
      mode: 0755

  - name: WEBサーバの設定ファイルが配置され、反映されている
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
      - restart httpd

  - name: WEBサーバのwelcome.confが削除されている
    file:
      path: /etc/httpd/conf.d/welcome.conf
      state: absent
    notify:
      - restart httpd

  - name: WEBサーバのプロセス(httpd)がブート時に自動起動している
    service:
      name: httpd
      state: started
      enabled: yes

  tags: httpd
