---
- block:
  - name: MySQLサーバの稼働に必要なパッケージがインストールされている
    yum: 
      name: "{{ item }}"
      state: installed
    with_items:
      - mysql-server
      - MySQL-python
      - mysql-devel
      - gcc

  - name: python mysqldb moduleがインストールされている
    pip:
      name: MySQL-Python

  - name: mysqldプロセスが起動している
    service: 
      name: mysqld
      state: started
      enabled: yes

  - name: wordpress用データベースが作成されている
    mysql_db:
      db: "{{ dbname }}"
      state: present
      encoding: utf8

  - name: wordpress用データベースに接続出来るアカウントが作成されている
    mysql_user: >
      name="{{ dbuser }}"
      password="{{ dbpassword }}"
      priv="{{ dbname }}.*:ALL"
      state=present

  tags: mysqld
