---
- block:
  - name: be sure mysql-server is installed
    yum: name={{item}} state=installed
    with_items:
      - mysql-server
      - MySQL-python
      - mysql-devel
      - gcc

  - name: be sure python mysqldb module installed
    pip:
      name: MySQL-Python

  - name: be sure mysqld is running and enabled
    service: name=mysqld state=started enabled=yes

  - name: Create database
    mysql_db: db={{dbname}} state=present encoding=utf8

  - name: Create database user
    mysql_user: >
      name={{dbuser}}
      password="{{dbpassword}}"
      priv={{dbname}}.*:ALL
      state=present

  tags: mysqld
