---
- block:
  - name: EPELリポジトリがインストールされている
    yum:
      name: epel-release

  - name: EPELリポジトリが無効化されている
    ini_file:
      dest: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: 0

  tags: epel
